### ISSUE TITLE
Document the exclusion of `src/DataFixtures/` for prod (dev dependency)

### ISSUE THREAD

**Issue by GromNaN** [doctrine/DoctrineFixturesBundle#537]
Fixture classes must implement the `Doctrine\Common\DataFixtures\FixtureInterface`. But this package is a "dev-dependency" that can be skipped for "prod" deployments.

When Symfony is configured to discover the `src/` directory, the fixture classes are automatically registered as service in the DIC. But when the `doctrine/data-fixtures` package is not installed, the files in `src/DataFixtures` cannot be included by PHP. And the container compilation fails.

A solution is to scan this directory only in `when@dev`.

```yaml
services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude: '../src/DataFixtures/'

when@dev:
    services:
        App\DataFixtures\:
            resource: '../src/DataFixtures/'
```

Using `#[WhenNot(env: 'prod')]` is not possible since the class cannot be loaded.

**Comment by mickverm** [comment]
I stumbled upon this issue when trying to find a solution for having to remove the `src/DataFixtures/` directory in CI before creating a prod release. So I tried this with `when@test`, but immediately ran into issues:

```yaml
services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude: '../src/DataFixtures/'

when@test:
    services:
        App\DataFixtures\:
            resource: '../src/DataFixtures/'
```

Trying to load the fixtures in the test environment fails to find the fixtures:

```shell
php bin/console doctrine:fixtures:load --env=test


 [ERROR] Could not find any fixture services to load.                                                                   
```                                                                                                

While they seem to be autowireable?

```shell
php bin/console debug:autowiring Fixture --all --env=test

Autowirable Types
=================

 The following classes & interfaces can be used as type-hints when autowiring:
 (only showing classes/interfaces matching Fixture)

 App\DataFixtures\XFixture

 App\DataFixtures\YFixture

 App\DataFixtures\ZFixture

 Pro-tip: use interfaces in your type-hints instead of classes to benefit from the dependency inversion principle.
```

Is there something I'm missing here?

**Comment by alexislefebvre** [comment]
What error did you encounter?

---

I had a weird error only when deploying a project:

```
 > post-install-cmd: @auto-scripts                                            
  > auto-scripts: Symfony\Flex\Flex->executeAutoScripts                        
  Executing script cache:clear                                                 
  Executed script cache:clear  [KO]                                            
   [KO]                                                                        
  Script cache:clear returned with error code 255                              
  !!  Symfony\Component\ErrorHandler\Error\ClassNotFoundError {#639            
  !!    #message: """                                                          
  !!      Attempted to load class "AbstractFixture" from namespace "Doctrine\  
  Common\DataFixtures".\n                                                      
  !!      Did you forget a "use" statement for another namespace?              
  !!      """                                                                  
  !!    #code: 0                                                               
  !!    #file: "./src/DataFixtures/ORM/Load100BadgeData.php"                   
  !!    #line: 13       
```

I wasn’t sure if it was due to Symfony services loading or `autoload` from Composer. This was in a personal project, so I chose the fastest solution and moved fixtures in `tests/`:

```yaml
when@test:
    services:
        App\Tests\DataFixtures\:
            resource: '../tests/DataFixtures/*'
            autowire: true
            tags: [ 'doctrine.fixture.orm' ]
```

And actually I prefer to not have tests data in `src/`. But that’s still a weird solution.

**Comment by alexislefebvre** [comment]
It may be related to: 

- https://github.com/symfony/symfony/issues/62545

**Comment by mickverm** [comment]
The only 'error' I have is `[ERROR] Could not find any fixture services to load.`, for reference `when@dev` also doesn't work.

**Comment by Marv51** [comment]
@mickverm I had the same issue that you are describing.
~~Removing the general `App\` part in services.yaml and instead only conditionally loading the classes like this works better for me:~~

```yaml
when@prod:
    services:
        App\:
            resource: '../src/'
            exclude: '../src/DataFixtures/'

when@dev:
    services:
        App\:
            resource: '../src/'

when@test:
    services:
        App\:
            resource: '../src/'
```

Update: Na, sorry. My setup is still broken, now it can't find my commands.

**Comment by vince83110** [comment]
What is a little crazy, is it worked for my project until Symfony 7.3.7 without any excluding for prod and including for dev, when trying to upgrade to Symfony 7.4.0, I face the error @alexislefebvre faced. I tried everything, I checked @alexislefebvre thread, it seems we are waiting for a patch, so the configuration won't be necessary.

If I exclude the repository in prod, I just have: 

> In ClassLoader.php line 576:                        
>   Class "Doctrine\Bundle\FixturesBundle\Fixture" not found.

I checked everywhere, no Fixture class is loaded except in DataFixtures namespace.
I understand @alexislefebvre solution, but I prefer to still use src/DataFixtures, as described in official documentation, it should works. Wait and see I guess.

**Comment by stof** [comment]
This may be fixed by https://github.com/symfony/symfony/pull/62544

**Comment by vince83110** [comment]
@stof the fix is merged, I tried, but still same error. Can't upgrade to SF 7.4 for now because of Fixtures, I tried many configurations, but still. 

I will require fixtures in "not dev" vendors, impossible to understand what is happening and we want to keep LTS versions. 

I hope someone will find the fix or upgrade the documentation.

**Comment by stof** [comment]
@vince83110 have you tried the 7.4.x-dev version of the Symfony component ? That fix is merged but not released yet.

**Comment by vince83110** [comment]
> [@vince83110](https://github.com/vince83110) have you tried the 7.4.x-dev version of the Symfony component ? That fix is merged but not released yet.

Yes I used the dev already, still the same:

>     #message: """
>       Attempted to load class "Fixture" from namespace "Doctrine\Bundle\FixturesBundle".\n
>       Did you forget a "use" statement for another namespace?
>       """

It's ok, I will load fixtures vendor in prod. I keep following this interesting thread.

**Comment by GromNaN** [comment]
This should be solved by https://github.com/symfony/symfony/pull/62675

**Comment by GromNaN** [comment]
Closing as not required. I thought that was the expected behavior, but it was a bug in Symfony 7.4.0.

**Comment by it-tabtrade** [comment]
> This should be solved by [symfony/symfony#62675](https://github.com/symfony/symfony/pull/62675)

This PR was merged to 6.4 instead of 7.4 and the issue is still there

**Comment by nicolas-grekas** [comment]
@it-tabtrade see how things work:

<img width="731" height="348" alt="Image" src="https://github.com/user-attachments/assets/0b1e44e6-0bc5-446c-be74-0fd92cc56591" />

From https://github.com/symfony/symfony/commits/8.1/

**Comment by it-tabtrade** [comment]
@nicolas-grekas works like a charm now. Thanks!
